// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srx_grpc.proto

package srx_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PduRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Length               uint32   `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PduRequest) Reset()         { *m = PduRequest{} }
func (m *PduRequest) String() string { return proto.CompactTextString(m) }
func (*PduRequest) ProtoMessage()    {}
func (*PduRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_srx_grpc_70ccabd431f0bed8, []int{0}
}
func (m *PduRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PduRequest.Unmarshal(m, b)
}
func (m *PduRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PduRequest.Marshal(b, m, deterministic)
}
func (dst *PduRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PduRequest.Merge(dst, src)
}
func (m *PduRequest) XXX_Size() int {
	return xxx_messageInfo_PduRequest.Size(m)
}
func (m *PduRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PduRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PduRequest proto.InternalMessageInfo

func (m *PduRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PduRequest) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type PduResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Length               uint32   `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	ValidationStatus     uint32   `protobuf:"varint,3,opt,name=validation_status,json=validationStatus,proto3" json:"validation_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PduResponse) Reset()         { *m = PduResponse{} }
func (m *PduResponse) String() string { return proto.CompactTextString(m) }
func (*PduResponse) ProtoMessage()    {}
func (*PduResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_srx_grpc_70ccabd431f0bed8, []int{1}
}
func (m *PduResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PduResponse.Unmarshal(m, b)
}
func (m *PduResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PduResponse.Marshal(b, m, deterministic)
}
func (dst *PduResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PduResponse.Merge(dst, src)
}
func (m *PduResponse) XXX_Size() int {
	return xxx_messageInfo_PduResponse.Size(m)
}
func (m *PduResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PduResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PduResponse proto.InternalMessageInfo

func (m *PduResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PduResponse) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *PduResponse) GetValidationStatus() uint32 {
	if m != nil {
		return m.ValidationStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*PduRequest)(nil), "srx_grpc.PduRequest")
	proto.RegisterType((*PduResponse)(nil), "srx_grpc.PduResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SRxApiClient is the client API for SRxApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SRxApiClient interface {
	SendPacketToSRxServer(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (*PduResponse, error)
	SendAndWaitProcess(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (SRxApi_SendAndWaitProcessClient, error)
}

type sRxApiClient struct {
	cc *grpc.ClientConn
}

func NewSRxApiClient(cc *grpc.ClientConn) SRxApiClient {
	return &sRxApiClient{cc}
}

func (c *sRxApiClient) SendPacketToSRxServer(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (*PduResponse, error) {
	out := new(PduResponse)
	err := c.cc.Invoke(ctx, "/srx_grpc.SRxApi/SendPacketToSRxServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRxApiClient) SendAndWaitProcess(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (SRxApi_SendAndWaitProcessClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SRxApi_serviceDesc.Streams[0], "/srx_grpc.SRxApi/SendAndWaitProcess", opts...)
	if err != nil {
		return nil, err
	}
	x := &sRxApiSendAndWaitProcessClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SRxApi_SendAndWaitProcessClient interface {
	Recv() (*PduResponse, error)
	grpc.ClientStream
}

type sRxApiSendAndWaitProcessClient struct {
	grpc.ClientStream
}

func (x *sRxApiSendAndWaitProcessClient) Recv() (*PduResponse, error) {
	m := new(PduResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SRxApiServer is the server API for SRxApi service.
type SRxApiServer interface {
	SendPacketToSRxServer(context.Context, *PduRequest) (*PduResponse, error)
	SendAndWaitProcess(*PduRequest, SRxApi_SendAndWaitProcessServer) error
}

func RegisterSRxApiServer(s *grpc.Server, srv SRxApiServer) {
	s.RegisterService(&_SRxApi_serviceDesc, srv)
}

func _SRxApi_SendPacketToSRxServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PduRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRxApiServer).SendPacketToSRxServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srx_grpc.SRxApi/SendPacketToSRxServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRxApiServer).SendPacketToSRxServer(ctx, req.(*PduRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRxApi_SendAndWaitProcess_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PduRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SRxApiServer).SendAndWaitProcess(m, &sRxApiSendAndWaitProcessServer{stream})
}

type SRxApi_SendAndWaitProcessServer interface {
	Send(*PduResponse) error
	grpc.ServerStream
}

type sRxApiSendAndWaitProcessServer struct {
	grpc.ServerStream
}

func (x *sRxApiSendAndWaitProcessServer) Send(m *PduResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SRxApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "srx_grpc.SRxApi",
	HandlerType: (*SRxApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPacketToSRxServer",
			Handler:    _SRxApi_SendPacketToSRxServer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendAndWaitProcess",
			Handler:       _SRxApi_SendAndWaitProcess_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "srx_grpc.proto",
}

func init() { proto.RegisterFile("srx_grpc.proto", fileDescriptor_srx_grpc_70ccabd431f0bed8) }

var fileDescriptor_srx_grpc_70ccabd431f0bed8 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2e, 0xaa, 0x88,
	0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x2c,
	0xb8, 0xb8, 0x02, 0x52, 0x4a, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58,
	0x52, 0x12, 0x4b, 0x12, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0xc0, 0x6c, 0x21, 0x31, 0x2e,
	0xb6, 0x9c, 0xd4, 0xbc, 0xf4, 0x92, 0x0c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xde, 0x20, 0x28, 0x4f,
	0x29, 0x8d, 0x8b, 0x1b, 0xac, 0xb3, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x95, 0x14, 0xad, 0x42, 0xda,
	0x5c, 0x82, 0x65, 0x89, 0x39, 0x99, 0x29, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xf1, 0xc5, 0x25, 0x89,
	0x25, 0xa5, 0xc5, 0x12, 0xcc, 0x60, 0x25, 0x02, 0x08, 0x89, 0x60, 0xb0, 0xb8, 0xd1, 0x74, 0x46,
	0x2e, 0xb6, 0xe0, 0xa0, 0x0a, 0xc7, 0x82, 0x4c, 0x21, 0x37, 0x2e, 0xd1, 0xe0, 0xd4, 0xbc, 0x94,
	0x80, 0xc4, 0xe4, 0xec, 0xd4, 0x92, 0x90, 0xfc, 0xe0, 0xa0, 0x8a, 0xe0, 0xd4, 0xa2, 0xb2, 0xd4,
	0x22, 0x21, 0x11, 0x3d, 0xb8, 0x07, 0x11, 0xbe, 0x91, 0x12, 0x45, 0x13, 0x85, 0xb8, 0x54, 0x89,
	0x41, 0xc8, 0x95, 0x4b, 0x08, 0x64, 0x8e, 0x63, 0x5e, 0x4a, 0x78, 0x62, 0x66, 0x49, 0x40, 0x51,
	0x7e, 0x72, 0x6a, 0x71, 0x31, 0x89, 0x86, 0x18, 0x30, 0x26, 0xb1, 0x81, 0x03, 0xd3, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x99, 0x29, 0x7f, 0xe5, 0x5e, 0x01, 0x00, 0x00,
}
